#!/usr/bin/env python3
"""Retrospectively apply the registered two-channel checkpoint stopping rule.

The script never trains or changes a policy. It reuses fixed SURV/FAIL rows from
an existing ``aw_wall_probe.py`` cache, evaluates the selected
``model_{step}.pt`` checkpoints in a run directory, and audits two failure
channels:

* contrast: wall-bin ``Delta_hat`` first crosses below ``tau`` after the contrast
  has previously formed (``Delta_hat >= 2 * tau``), and
* level: target-Q minimum first falls more than ``abs(level_offset)`` below its
  median baseline in the registered early window.

The adopted checkpoint is the latest checkpoint strictly before the first
channel fires. No probe rows, labels, sidecar weights, or batch normalization
statistics are generated by this script.
"""

from __future__ import annotations

import argparse
import csv
import gc
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import h5py
import numpy as np

from aw_wall_probe import batched, build_scorer, find_key, select_checkpoint_grid


CHECKPOINT_PATTERN = re.compile(r"^model_(\d+)\.pt$")
AGENT_TYPES = ("cql", "aw_cql", "iql", "td3bc", "dw")
DEFAULT_BASELINE_WINDOW = "5k-20k"


@dataclass(frozen=True)
class RunSpec:
    label: str
    ckpt_dir: Path
    dataset: Path
    probe_rows: Path
    wall_bins: tuple[int, ...]
    agent_type: str
    tau: float
    level_offset: float
    baseline_window: tuple[int, int]
    level_from_log: Path | None
    out: Path
    device: str
    batch_size: int
    checkpoint_grid: str | None = None


@dataclass(frozen=True)
class ProbeData:
    reward_hash: str
    span_critic_obs: np.ndarray
    span_actions: np.ndarray
    cells: dict[tuple[int, str], tuple[np.ndarray, np.ndarray]]


def parse_step(value: str | int | float) -> int:
    """Parse checkpoint/window steps such as ``5000``, ``5k``, or ``0.3m``."""
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        if not value.is_integer():
            raise ValueError(f"step must be integral, got {value}")
        return int(value)
    text = str(value).strip().lower().replace("_", "")
    match = re.fullmatch(r"([0-9]+(?:\.[0-9]+)?)([km]?)", text)
    if match is None:
        raise ValueError(f"invalid step value: {value!r}")
    scale = {"": 1, "k": 1_000, "m": 1_000_000}[match.group(2)]
    parsed = float(match.group(1)) * scale
    if not parsed.is_integer():
        raise ValueError(f"step must be integral, got {value!r}")
    return int(parsed)


def parse_window(value: str | tuple[int, int] | list[int]) -> tuple[int, int]:
    if isinstance(value, (tuple, list)):
        if len(value) != 2:
            raise ValueError(f"baseline window requires two endpoints, got {value!r}")
        start, end = parse_step(value[0]), parse_step(value[1])
    else:
        normalized = str(value).replace("–", "-").replace("—", "-").replace(" ", "")
        parts = normalized.split("-")
        if len(parts) != 2:
            raise ValueError(f"invalid baseline window {value!r}; expected 5k-20k")
        start, end = parse_step(parts[0]), parse_step(parts[1])
    if start > end:
        raise ValueError(f"baseline window start exceeds end: {start} > {end}")
    return start, end


def discover_checkpoints(directory: Path) -> list[tuple[int, Path]]:
    if not directory.is_dir():
        raise NotADirectoryError(f"checkpoint directory not found: {directory}")
    paths = list(directory.glob("model_*.pt"))
    if not paths:
        paths = list(directory.rglob("model_*.pt"))
    by_step: dict[int, Path] = {}
    for path in paths:
        match = CHECKPOINT_PATTERN.fullmatch(path.name)
        if match is None:
            continue
        step = int(match.group(1))
        if step in by_step:
            raise ValueError(
                f"duplicate checkpoint step {step}: {by_step[step]} and {path}"
            )
        by_step[step] = path
    if not by_step:
        raise FileNotFoundError(f"no model_{{step}}.pt checkpoints found under {directory}")
    return sorted(by_step.items())


def _reward_hash(reward_dataset: h5py.Dataset) -> str:
    import hashlib

    count = int(reward_dataset.shape[0])
    head = np.asarray(reward_dataset[: min(1_000, count)]).squeeze().astype(np.float64)
    tail = np.asarray(reward_dataset[max(0, count - 1_000) :]).squeeze().astype(np.float64)
    return hashlib.sha256(
        np.ascontiguousarray(head).tobytes() + np.ascontiguousarray(tail).tobytes()
    ).hexdigest()[:16]


def _cache_hash(cache: np.lib.npyio.NpzFile) -> str:
    if "rhash" not in cache:
        raise KeyError("probe cache has no rhash; refusing an unpaired audit")
    return str(np.asarray(cache["rhash"]).item())


def _read_rows(dataset: h5py.Dataset, indices: np.ndarray) -> np.ndarray:
    rows = np.asarray(indices, dtype=np.int64).reshape(-1)
    if rows.size == 0:
        raise ValueError("probe cell contains zero rows")
    if np.any(rows[1:] < rows[:-1]):
        rows = np.sort(rows)
    return np.asarray(dataset[rows])


def load_fixed_probe_data(spec: RunSpec) -> ProbeData:
    """Load only cached rows and reject any dataset/cache pairing mismatch."""
    if not spec.dataset.is_file():
        raise FileNotFoundError(f"dataset not found: {spec.dataset}")
    if not spec.probe_rows.is_file():
        raise FileNotFoundError(f"probe row cache not found: {spec.probe_rows}")

    with np.load(spec.probe_rows, allow_pickle=True) as cache:
        required = {"cell_keys", "cell_idx", "span_idx", "rhash"}
        missing = sorted(required.difference(cache.files))
        if missing:
            raise KeyError(f"probe cache is missing required keys: {missing}")
        cached_hash = _cache_hash(cache)
        cached_cells = {
            (int(key[0]), str(key[1])): np.asarray(indices, dtype=np.int64).reshape(-1)
            for key, indices in zip(cache["cell_keys"], cache["cell_idx"])
        }
        span_indices = np.asarray(cache["span_idx"], dtype=np.int64).reshape(-1)

    required_cells = {
        (phase_bin, label)
        for phase_bin in spec.wall_bins
        for label in ("SURV", "FAIL")
    }
    missing_cells = sorted(required_cells.difference(cached_cells))
    if missing_cells:
        raise KeyError(
            f"probe cache lacks requested fixed cells {missing_cells}; "
            "regenerating labels is intentionally forbidden"
        )
    if span_indices.size == 0:
        raise ValueError("probe cache span_idx is empty")

    with h5py.File(spec.dataset, "r") as h5:
        reward_key = find_key(h5, ["rewards", "reward"])
        obs_key = find_key(
            h5,
            ["observations", "obs", "actor_observations", "policy_observations"],
        )
        critic_obs_key = find_key(h5, ["critic_observations", "critic_obs"]) or obs_key
        action_key = find_key(h5, ["actions", "action"])
        if reward_key is None or critic_obs_key is None or action_key is None:
            raise KeyError(
                "dataset must contain rewards, critic observations (or observations), and actions"
            )
        count = int(h5[reward_key].shape[0])
        actual_hash = _reward_hash(h5[reward_key])
        if actual_hash != cached_hash:
            raise ValueError(
                f"rhash mismatch: probe cache has {cached_hash}, dataset has {actual_hash}"
            )
        all_indices = [span_indices, *[cached_cells[key] for key in required_cells]]
        for indices in all_indices:
            if np.any(indices < 0) or np.any(indices >= count):
                raise IndexError(f"probe cache contains a row outside dataset range [0, {count})")

        span_critic_obs = _read_rows(h5[critic_obs_key], span_indices)
        span_actions = _read_rows(h5[action_key], span_indices)
        cells = {
            key: (
                _read_rows(h5[critic_obs_key], cached_cells[key]),
                _read_rows(h5[action_key], cached_cells[key]),
            )
            for key in required_cells
        }

    print(
        f"[{spec.label}] paired dataset/probe rows: rhash={actual_hash} "
        f"span={len(span_indices):,}"
    )
    return ProbeData(actual_hash, span_critic_obs, span_actions, cells)


def _normalized_column(name: str) -> str:
    return name.strip().lower().replace(" ", "_")


def load_level_log(path: Path) -> dict[int, float]:
    """Load q_target_min from a W&B/TensorBoard-exported CSV."""
    if not path.is_file():
        raise FileNotFoundError(f"level log CSV not found: {path}")
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise ValueError(f"level log CSV has no header: {path}")
        fields = list(reader.fieldnames)
        normalized = {_normalized_column(field): field for field in fields}
        step_field = next(
            (
                normalized[name]
                for name in ("step", "global_step", "_step")
                if name in normalized
            ),
            None,
        )
        level_field = next(
            (
                field
                for field in fields
                if _normalized_column(field).split("/")[-1] == "q_target_min"
            ),
            None,
        )
        if step_field is None or level_field is None:
            raise KeyError(
                f"could not identify step/q_target_min columns in {path}; fields={fields}"
            )
        values: dict[int, float] = {}
        for row in reader:
            try:
                step = int(float(row[step_field]))
                level = float(row[level_field])
            except (TypeError, ValueError):
                continue
            if math.isfinite(level):
                values[step] = level
    if not values:
        raise ValueError(f"no finite q_target_min rows found in {path}")
    return values


def level_at_checkpoint(log_values: dict[int, float], step: int) -> tuple[float, int]:
    """Use the exact log step or the latest logged value at/before a checkpoint."""
    if step in log_values:
        return log_values[step], step
    previous = [logged_step for logged_step in log_values if logged_step <= step]
    if not previous:
        raise ValueError(f"level log has no value at or before checkpoint step {step}")
    log_step = max(previous)
    return log_values[log_step], log_step


def scorer_agent_type(agent_type: str) -> str:
    if agent_type in {"cql", "aw_cql", "dw"}:
        return "cql"
    return agent_type


def scan_stopping_rule(
    rows: list[dict[str, Any]],
    *,
    main_bin: int,
    tau: float,
    level_offset: float,
    baseline_window: tuple[int, int],
) -> dict[str, Any]:
    """Apply the preregistered warmup-gated contrast and level triggers."""
    if not rows:
        raise ValueError("cannot audit an empty checkpoint sequence")
    level_rows = [
        row["q_min"]
        for row in rows
        if baseline_window[0] <= row["step"] <= baseline_window[1]
        and math.isfinite(row["q_min"])
    ]
    if not level_rows:
        raise ValueError(
            "no finite q_min checkpoint lies inside baseline window "
            f"[{baseline_window[0]}, {baseline_window[1]}]"
        )
    baseline = float(np.median(level_rows))
    level_threshold = baseline - abs(level_offset)

    contrast_step: int | None = None
    level_step: int | None = None
    armed = False
    previous_dhat: float | None = None
    peak = -math.inf
    dhat_key = f"dhat_bin{main_bin}"

    for row in rows:
        row["contrast_fired"] = 0
        row["level_fired"] = 0
        dhat = float(row[dhat_key])
        if math.isfinite(dhat):
            if contrast_step is None:
                peak = max(peak, dhat)
            if (
                contrast_step is None
                and armed
                and previous_dhat is not None
                and previous_dhat >= tau
                and dhat < tau
            ):
                contrast_step = int(row["step"])
                row["contrast_fired"] = 1
            if dhat >= 2.0 * tau:
                armed = True
            previous_dhat = dhat

        q_min = float(row["q_min"])
        if level_step is None and math.isfinite(q_min) and q_min < level_threshold:
            level_step = int(row["step"])
            row["level_fired"] = 1

    firing_steps = [step for step in (contrast_step, level_step) if step is not None]
    t_fire = min(firing_steps) if firing_steps else None
    if t_fire is None:
        adopted = int(rows[-1]["step"])
        fired_channel = "none"
        gap = None
    else:
        prior_steps = [int(row["step"]) for row in rows if int(row["step"]) < t_fire]
        adopted = max(prior_steps) if prior_steps else None
        if contrast_step == t_fire and level_step == t_fire:
            fired_channel = "contrast+level"
        elif contrast_step == t_fire:
            fired_channel = "contrast"
        else:
            fired_channel = "level"
        gap = t_fire - adopted if adopted is not None else None

    return {
        "t_fire": t_fire,
        "fired_channel": fired_channel,
        "adopted_ckpt": adopted,
        "gap": gap,
        "warmup_peak_dhat": peak if math.isfinite(peak) else None,
        "contrast_fire_step": contrast_step,
        "level_fire_step": level_step,
        "level_baseline": baseline,
        "level_threshold": level_threshold,
        "baseline_window_start": baseline_window[0],
        "baseline_window_end": baseline_window[1],
    }


def write_audit_csv(
    spec: RunSpec,
    rows: list[dict[str, Any]],
    summary: dict[str, Any],
) -> None:
    spec.out.parent.mkdir(parents=True, exist_ok=True)
    dhat_fields = [f"dhat_bin{phase_bin}" for phase_bin in spec.wall_bins]
    fields = [
        "row_type",
        "run",
        "agent_type",
        "step",
        *dhat_fields,
        "span",
        "q_min",
        "q_min_source",
        "q_min_log_step",
        "contrast_fired",
        "level_fired",
        "t_fire",
        "fired_channel",
        "adopted_ckpt",
        "gap",
        "warmup_peak_dhat",
        "contrast_fire_step",
        "level_fire_step",
        "level_baseline",
        "level_threshold",
        "baseline_window_start",
        "baseline_window_end",
    ]
    with spec.out.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "row_type": "checkpoint",
                    "run": spec.label,
                    "agent_type": spec.agent_type,
                    **row,
                }
            )
        writer.writerow(
            {
                "row_type": "summary",
                "run": spec.label,
                "agent_type": spec.agent_type,
                **summary,
            }
        )


def audit_run(spec: RunSpec) -> dict[str, Any]:
    checkpoints = select_checkpoint_grid(
        discover_checkpoints(spec.ckpt_dir),
        spec.checkpoint_grid,
        label=spec.label,
    )
    probe = load_fixed_probe_data(spec)
    log_values = load_level_log(spec.level_from_log) if spec.level_from_log else None
    scorer_type = scorer_agent_type(spec.agent_type)
    rows: list[dict[str, Any]] = []

    for step, checkpoint_path in checkpoints:
        scorer = build_scorer(
            scorer_type,
            str(checkpoint_path),
            spec.device,
            include_target_q=log_values is None,
        )
        if log_values is None:
            q_fn, _, target_q_fn = scorer
        else:
            q_fn, _ = scorer
            target_q_fn = None

        span_q = batched(
            q_fn,
            probe.span_critic_obs,
            probe.span_actions,
            bs=spec.batch_size,
        )
        span = float(np.percentile(span_q, 99) - np.percentile(span_q, 1))
        row: dict[str, Any] = {
            "step": step,
            "span": span,
            "contrast_fired": 0,
            "level_fired": 0,
        }
        for phase_bin in spec.wall_bins:
            surv_obs, surv_actions = probe.cells[(phase_bin, "SURV")]
            fail_obs, fail_actions = probe.cells[(phase_bin, "FAIL")]
            q_surv = batched(q_fn, surv_obs, surv_actions, bs=spec.batch_size)
            q_fail = batched(q_fn, fail_obs, fail_actions, bs=spec.batch_size)
            delta = float(q_surv.mean() - q_fail.mean())
            row[f"dhat_bin{phase_bin}"] = delta / max(span, 1e-12)

        if log_values is not None:
            q_min, log_step = level_at_checkpoint(log_values, step)
            row.update(
                q_min=q_min,
                q_min_source="log:q_target_min",
                q_min_log_step=log_step,
            )
        else:
            assert target_q_fn is not None
            target_q = batched(
                target_q_fn,
                probe.span_critic_obs,
                probe.span_actions,
                bs=spec.batch_size,
            )
            row.update(
                q_min=float(np.min(target_q)),
                q_min_source="probe:target_twin_min_q_data",
                q_min_log_step="",
            )
        rows.append(row)
        main_dhat = row[f"dhat_bin{spec.wall_bins[0]}"]
        print(
            f"[{spec.label} @{step}] dhat_bin{spec.wall_bins[0]}={main_dhat:+.6f} "
            f"span={span:.6f} q_min={row['q_min']:.6f}"
        )

        del scorer, q_fn, target_q_fn
        gc.collect()
        try:
            from holosoma.utils.safe_torch_import import torch

            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        except ImportError:
            pass

    summary = scan_stopping_rule(
        rows,
        main_bin=spec.wall_bins[0],
        tau=spec.tau,
        level_offset=spec.level_offset,
        baseline_window=spec.baseline_window,
    )
    write_audit_csv(spec, rows, summary)
    fire_text = "None" if summary["t_fire"] is None else str(summary["t_fire"])
    print(
        f"[{spec.label}] t_fire={fire_text} channel={summary['fired_channel']} "
        f"-> adopted={summary['adopted_ckpt']} gap={summary['gap']} out={spec.out}"
    )
    return summary


def _value(mapping: dict[str, Any], key: str, default: Any = None) -> Any:
    return mapping.get(key, mapping.get(key.replace("_", "-"), default))


def _path(value: str | Path | None, base: Path) -> Path | None:
    if value in (None, ""):
        return None
    path = Path(value).expanduser()
    return path if path.is_absolute() else (base / path)


def run_spec_from_mapping(
    mapping: dict[str, Any],
    *,
    defaults: dict[str, Any],
    base: Path,
    index: int,
) -> RunSpec:
    merged = {**defaults, **mapping}
    label = str(_value(merged, "label", f"run-{index}"))
    ckpt_dir = _path(_value(merged, "ckpt_dir"), base)
    dataset = _path(_value(merged, "dataset"), base)
    probe_rows = _path(_value(merged, "probe_rows"), base)
    if ckpt_dir is None or dataset is None or probe_rows is None:
        raise ValueError(f"batch run {label!r} requires ckpt_dir, dataset, and probe_rows")
    wall_bins_raw = _value(merged, "wall_bins")
    if wall_bins_raw is None:
        raise ValueError(f"batch run {label!r} requires wall_bins")
    wall_bins = tuple(int(value) for value in wall_bins_raw)
    if not wall_bins:
        raise ValueError(f"batch run {label!r} has no wall_bins")
    agent_type = str(_value(merged, "agent_type"))
    if agent_type not in AGENT_TYPES:
        raise ValueError(f"batch run {label!r} has invalid agent_type={agent_type!r}")
    out = _path(
        _value(merged, "out", f"stopping_rule_audit_{re.sub(r'[^A-Za-z0-9_.-]+', '_', label)}.csv"),
        base,
    )
    assert out is not None
    return RunSpec(
        label=label,
        ckpt_dir=ckpt_dir,
        dataset=dataset,
        probe_rows=probe_rows,
        wall_bins=wall_bins,
        agent_type=agent_type,
        tau=float(_value(merged, "tau", 0.05)),
        level_offset=float(_value(merged, "level_offset", -30.0)),
        baseline_window=parse_window(
            _value(merged, "level_baseline_window", DEFAULT_BASELINE_WINDOW)
        ),
        level_from_log=_path(_value(merged, "level_from_log"), base),
        out=out,
        device=str(_value(merged, "device", "cuda")),
        batch_size=int(_value(merged, "batch_size", 4096)),
        checkpoint_grid=_value(merged, "steps"),
    )


def load_batch_specs(path: Path) -> list[RunSpec]:
    import yaml

    with path.open(encoding="utf-8") as handle:
        document = yaml.safe_load(handle)
    if not isinstance(document, dict) or not isinstance(document.get("runs"), list):
        raise ValueError("batch YAML must contain a top-level 'runs' list")
    defaults = document.get("defaults") or {}
    if not isinstance(defaults, dict):
        raise ValueError("batch YAML 'defaults' must be a mapping")
    base = path.resolve().parent
    return [
        run_spec_from_mapping(run, defaults=defaults, base=base, index=index)
        for index, run in enumerate(document["runs"], start=1)
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ckpt-dir")
    parser.add_argument("--dataset")
    parser.add_argument("--probe-rows")
    parser.add_argument("--wall-bins", type=int, nargs="+")
    parser.add_argument("--agent-type", choices=AGENT_TYPES)
    parser.add_argument("--tau", type=float, default=0.05)
    parser.add_argument("--level-offset", type=float, default=-30.0)
    parser.add_argument("--level-baseline-window", default=DEFAULT_BASELINE_WINDOW)
    parser.add_argument(
        "--level-from-log",
        help="optional CSV containing step/global_step and q_target_min; preferred over probe fallback",
    )
    parser.add_argument("--out")
    parser.add_argument("--run-label")
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--batch-size", type=int, default=4096)
    parser.add_argument(
        "--steps",
        help=(
            "checkpoint grid; comma-separated exact steps and inclusive saved ranges, "
            "e.g. 20k,60k,180k:220k,300k"
        ),
    )
    parser.add_argument("--batch-config", help="YAML with defaults and a runs list")
    return parser.parse_args()


def direct_spec(args: argparse.Namespace) -> RunSpec:
    missing = [
        name
        for name in ("ckpt_dir", "dataset", "probe_rows", "wall_bins", "agent_type", "out")
        if getattr(args, name) in (None, [])
    ]
    if missing:
        raise ValueError(
            "direct mode is missing required arguments: "
            + ", ".join("--" + name.replace("_", "-") for name in missing)
        )
    ckpt_dir = Path(args.ckpt_dir).expanduser()
    return RunSpec(
        label=args.run_label or ckpt_dir.name,
        ckpt_dir=ckpt_dir,
        dataset=Path(args.dataset).expanduser(),
        probe_rows=Path(args.probe_rows).expanduser(),
        wall_bins=tuple(args.wall_bins),
        agent_type=args.agent_type,
        tau=args.tau,
        level_offset=args.level_offset,
        baseline_window=parse_window(args.level_baseline_window),
        level_from_log=Path(args.level_from_log).expanduser() if args.level_from_log else None,
        out=Path(args.out).expanduser(),
        device=args.device,
        batch_size=args.batch_size,
        checkpoint_grid=args.steps,
    )


def main() -> int:
    args = parse_args()
    if args.batch_config:
        specs = load_batch_specs(Path(args.batch_config).expanduser().resolve())
    else:
        specs = [direct_spec(args)]
    for spec in specs:
        audit_run(spec)
    return 0


if __name__ == "__main__":
    sys.exit(main())
