import dataclasses
from holosoma.config_types.algo import (
    BCAlgoConfig,
    BCConfig,
    CODACAlgoConfig,
    CODACConfig,
    FastSACAlgoConfig,
    FastSACConfig,
    IQLAlgoConfig,
    IQLConfig,
    LayerConfig,
    ModuleConfig,
    OfflineSACAlgoConfig,
    OfflineSACConfig,
    OptimizerConfig,
    PPOAlgoConfig,
    PPOConfig,
    PPOModuleDictConfig,
    BFCQLAlgoConfig,
    BFCQLConfig,
    CQLAlgoConfig,
    VCCQLAlgoConfig,
    AWCQLAlgoConfig,
    MCQAlgoConfig,
    MCQConfig,
    CALQLAlgoConfig,
    OS_CQLAlgoConfig,
    OS_CALQLAlgoConfig,
    CQLConfig,
    VCCQLConfig,
    AWCQLConfig,
    CALQLConfig,
    OS_CQLConfig,
    OS_CALQLConfig,
    TD3BCAlgoConfig,
    TD3BCConfig,
)

ppo = PPOAlgoConfig(
    _target_="holosoma.agents.ppo.ppo.PPO",
    _recursive_=False,
    config=PPOConfig(
        num_learning_epochs=8,
        num_mini_batches=4,
        clip_param=0.2,
        gamma=0.99,
        lam=0.95,
        value_loss_coef=1.0,
        entropy_coef=0.01,
        actor_learning_rate=1e-5,
        actor_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=0.001),
        critic_learning_rate=1e-5,
        critic_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=0.001),
        max_grad_norm=1.0,
        schedule="adaptive",
        desired_kl=0.01,
        use_symmetry=True,
        symmetry_actor_coef=1.0,
        symmetry_critic_coef=0.0,
        num_steps_per_env=24,
        save_interval=100,
        load_optimizer=True,
        init_noise_std=0.8,
        num_learning_iterations=1000000,
        init_at_random_ep_len=True,
        eval_callbacks=None,
        module_dict=PPOModuleDictConfig(
            actor=ModuleConfig(
                type="MLP",
                input_dim=["actor_obs"],
                output_dim=["robot_action_dim"],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
            critic=ModuleConfig(
                type="MLP",
                input_dim=["critic_obs"],
                output_dim=[1],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
        ),
    ),
)

fast_sac = FastSACAlgoConfig(
    _target_="holosoma.agents.fast_sac.fast_sac_agent.FastSACAgent",
    _recursive_=False,
    config=FastSACConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=8192,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=False,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        episode_data_active_envs=64,
        episode_data_mc_gamma=None,
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

fast_sac_episode_data = dataclasses.replace(
    fast_sac,
    _target_="holosoma.agents.fast_sac.fast_sac_episode_data.FastSACEpisodeDataAgent",
)

fixed_fast_sac = dataclasses.replace(
    fast_sac,
    _target_="holosoma.agents.fixed_fast_sac.fast_sac_agent.FastSACAgent",
)

offline_sac = OfflineSACAlgoConfig(
    _target_="holosoma.agents.offline_sac.offline_sac_agent.OfflineSACAgent",
    _recursive_=False,
    config=OfflineSACConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        gamma=0.97,
        tau=0.125,
        batch_size=8192,
        num_updates=8,
        eval_interval=1000,
        policy_frequency=4,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=False,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        offline_block_size=65536,
        offline_buffer_capacity=262144,
        offline_refill_threshold=65536,
        offline_pin_memory=True,
        offline_shuffle_block_order=True,
        use_gpu_cache=False,
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

codac = CODACAlgoConfig(
    _target_="holosoma.agents.CODAC.CODAC_agent.CODACAgent",
    _recursive_=False,
    config=CODACConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        gamma=0.97,
        tau=0.125,
        batch_size=8192,
        num_updates=8,
        eval_interval=1000,
        policy_frequency=4,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=False,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        offline_block_size=65536,
        offline_buffer_capacity=262144,
        offline_refill_threshold=65536,
        offline_pin_memory=True,
        offline_shuffle_block_order=True,
        use_gpu_cache=False,
        conservative_weight=1.0,
        conservative_temperature=1.0,
        num_action_samples=10,
        use_lagrange=False,
        target_action_gap=10.0,
        cql_lagrange_init=1.0,
        cql_lagrange_learning_rate=3e-4,
        cql_lagrange_max=1e6,
        actor_q_aggregation="min",
        critic_conservative_mode="mean_q_stage1",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)


cql = CQLAlgoConfig(
    _target_="holosoma.agents.cql.cql_agent.CQLAgent",
    _recursive_=False,
    config=CQLConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=1024,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        eval_interval=1000,
        cql_num_action_samples=10,
        cql_temperature=1.0,
        cql_weight=5.0,
        dr3_weight=0.0,
        dr3_normalize_features=False,
        use_lagrange=False,
        cql_target_action_gap=10.0,
        cql_lagrange_learning_rate=3e-4,
        cql_lagrange_init=1.0,
        cql_lagrange_max=1e6,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        quantile_huber_kappa=1.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        use_gpu_cache = True,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

_vc_cql_config_values = dataclasses.asdict(cql.config)
_vc_cql_config_values.update(
    compile=False,
    alpha_init=0.3,
    use_autotune=False,
    vc_rank=4,
    vc_num_probes=32,
    vc_probe_std=0.25,
    vc_q_temperature=1.0,
    vc_q_tolerance=1.0,
    vc_contour_weight=1.0,
    vc_margin_gating=True,
    vc_target_margin=0.0,
    vc_cov_epsilon=1e-4,
    vc_cov_shrinkage=0.5,
    vc_cov_max_condition=100.0,
    vc_max_trace_ratio=2.0,
    vc_factor_max=1.0,
)
vc_cql = VCCQLAlgoConfig(
    _target_="holosoma.agents.vc_cql.vc_cql_agent.VCCQLAgent",
    _recursive_=False,
    config=VCCQLConfig(**_vc_cql_config_values),
)

# AW-CQL v0: identical hyperparameters to scalar CQL; the only difference is the
# agent class, which scales the conservative bracket by precomputed sidecar weights.
aw_cql = AWCQLAlgoConfig(
    _target_="holosoma.agents.aw_cql.aw_cql_agent.AWCQLAgent",
    _recursive_=False,
    config=AWCQLConfig(**dataclasses.asdict(cql.config)),
)


mcq = MCQAlgoConfig(
    _target_="holosoma.agents.mcq.mcq_agent.MCQAgent",
    _recursive_=False,
    config=MCQConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=1024,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        eval_interval=1000,
        cql_num_action_samples=10,
        cql_temperature=1.0,
        cql_weight=0.0,
        dr3_weight=0.0,
        dr3_normalize_features=False,
        use_lagrange=False,
        cql_target_action_gap=10.0,
        cql_lagrange_learning_rate=3e-4,
        cql_lagrange_init=1.0,
        cql_lagrange_max=1e6,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        quantile_huber_kappa=1.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        # training_metrics.add inside the MCQ critic step graph-breaks under
        # torch.compile; keep it off by default for MCQ.
        compile=False,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        use_gpu_cache=True,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
        mcq_lambda=0.9,
        mcq_num_action_samples=10,
        mcq_num_ood_samples=1,
        vae_hidden_dim=512,
        vae_latent_dim=0,
        vae_learning_rate=1e-3,
        vae_kl_weight=0.5,
    ),
)


bf_cql = BFCQLAlgoConfig(
    _target_="holosoma.agents.bf_cql.bf_cql_agent.BFCQLAgent",
    _recursive_=False,
    config=BFCQLConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=1024,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        eval_interval=1000,
        cql_num_action_samples=10,
        cql_temperature=1.0,
        cql_weight=5.0,
        bf_cql_action_grouping="coarse_5",
        ood_actor_num=1,
        use_lagrange=False,
        cql_target_action_gap=10.0,
        cql_lagrange_learning_rate=3e-4,
        cql_lagrange_init=1.0,
        cql_lagrange_max=1e6,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        quantile_huber_kappa=1.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        use_gpu_cache=True,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)


cal_ql = CALQLAlgoConfig(
    _target_="holosoma.agents.cal_ql.cal_ql_agent.CALQLAgent",
    _recursive_=False,
    config=CALQLConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=1024,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        eval_interval=1000,
        cql_num_action_samples=10,
        cql_temperature=1.0,
        cql_weight=5.0,
        calql_use_mc_return=True,
        calql_require_mc_return=True,
        calql_validate_complete_episodes=True,
        calql_mc_gamma=None,
        use_lagrange=False,
        cql_target_action_gap=10.0,
        cql_lagrange_learning_rate=3e-4,
        cql_lagrange_init=1.0,
        cql_lagrange_max=1e6,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        quantile_huber_kappa=1.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        use_gpu_cache=True,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
        offline_pretrain_steps=30000,
        online_total_steps=50000,
        online_eval_interval=0,
        online_warmup_steps=1000,
        online_collect_steps=1,
        updates_per_collect=1,
        online_buffer_size=524288,
        online_random_warmup=False,
        mixing_ratio_schedule="fixed",
        offline_mixing_ratio=0.5,
        offline_mixing_start=0.5,
        offline_mixing_end=0.0,
        mixing_anneal_steps=10000,
    ),
)

# os cql

os_cql = OS_CQLAlgoConfig(
    _target_="holosoma.agents.cql.os_cql_agent.OS_CQLAgent",
    _recursive_=False,
    config=OS_CQLConfig(
                num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=1024,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        eval_interval=1000,
        cql_num_action_samples=10,
        cql_temperature=1.0,
        cql_weight=5.0,
        use_lagrange=False,
        cql_target_action_gap=10.0,
        cql_lagrange_learning_rate=3e-4,
        cql_lagrange_init=1.0,
        cql_lagrange_max=1e6,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        quantile_huber_kappa=1.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        use_gpu_cache=True,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
        offline_pretrain_steps=30000,
        online_total_steps=50000,
        online_warmup_steps=1000,
        online_collect_steps=1,
        updates_per_collect=1,
        online_buffer_size=524288,
        online_random_warmup=False,
        mixing_ratio_schedule="fixed",
        offline_mixing_ratio=0.5,
        offline_mixing_start=0.5,
        offline_mixing_end=0.0,
        mixing_anneal_steps=10000,
        cql_gap_margin  = 5,
        cql_gap_softplus_tau  = 10,
        use_softplus = False,
    ),
)

os_cal_ql = OS_CALQLAlgoConfig(
    _target_="holosoma.agents.cal_ql.os_cal_ql_agent.OS_CALQLAgent",
    _recursive_=False,
    config=OS_CALQLConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-5,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=1024,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        eval_interval=1000,
        cql_num_action_samples=10,
        cql_temperature=1.0,
        cql_weight=5.0,
        calql_use_mc_return=True,
        calql_require_mc_return=True,
        calql_validate_complete_episodes=True,
        calql_mc_gamma=None,
        use_lagrange=False,
        cql_target_action_gap=10.0,
        cql_lagrange_learning_rate=3e-4,
        cql_lagrange_init=1.0,
        cql_lagrange_max=1e6,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        quantile_huber_kappa=1.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        use_gpu_cache=True,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
        offline_pretrain_steps=30000,
        online_total_steps=50000,
        online_eval_interval=0,
        online_warmup_steps=1000,
        online_collect_steps=1,
        updates_per_collect=1,
        online_buffer_size=524288,
        online_random_warmup=False,
        mixing_ratio_schedule="fixed",
        offline_mixing_ratio=0.5,
        offline_mixing_start=0.5,
        offline_mixing_end=0.0,
        mixing_anneal_steps=10000,
        cql_gap_margin  = 5,
        cql_gap_softplus_tau  = 10,
        use_softplus = False,
    ),
)



iql = IQLAlgoConfig(
    _target_="holosoma.agents.iql.iql_agent.IQLAgent",
    _recursive_=False,
    config=IQLConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        value_learning_rate=3e-4,
        actor_learning_rate=3e-4,
        batch_size=8192,
        num_updates=8,
        eval_interval=1000,
        discount=0.97,
        tau=0.005,
        expectile=0.7,
        beta=3.0,
        max_weight=100.0,
        critic_hidden_dim=768,
        value_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

bc = BCAlgoConfig(
    _target_="holosoma.agents.bc.bc_agent.BCAgent",
    _recursive_=False,
    config=BCConfig(
        num_learning_iterations=50000,
        actor_learning_rate=3e-4,
        batch_size=8192,
        num_updates=8,
        eval_interval=1000,
        actor_hidden_dim=512,
        use_symmetry=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

td3_bc = TD3BCAlgoConfig(
    _target_="holosoma.agents.td3.td3_agent.TD3BCAgent",
    _recursive_=False,
    config=TD3BCConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-4,
        batch_size=8192,
        num_updates=8,
        eval_interval=1000,
        discount=0.97,
        tau=0.005,
        policy_delay=2,
        target_policy_noise=0.2,
        target_noise_clip=0.5,
        td3bc_alpha=2.5,
        use_adaptive_lambda=True,
        bc_coef=1.0,
        actor_bc_warmup_steps=1000,
        td3bc_lambda_min=0.0,
        td3bc_lambda_max=10.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        use_tanh=True,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        offline_dataset_path="offline_data/fastsac_dataset.h5",
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

DEFAULTS = {
    "ppo": ppo,
    "fast_sac": fast_sac,
    "fast_sac_episode_data": fast_sac_episode_data,
    "fixed_fast_sac": fixed_fast_sac,
    "offline_sac": offline_sac,
    "codac": codac,
    "cql": cql,
    "vc_cql": vc_cql,
    "aw_cql": aw_cql,
    "mcq": mcq,
    "cal_ql": cal_ql,
    "os_cql": os_cql,
    "os_cal_ql": os_cal_ql,
    "bf_cql": bf_cql,
    "iql": iql,
    "bc": bc,
    "td3_bc": td3_bc,
}
